version: "3.9"
services:
  postgres:
    container_name: postgres_blog
    image: "postgres:14.4"
    user: 1000:1000  # current user (pablo). Get this info with $(id -u):$(id -g)
    volumes:
      - /etc/passwd:/etc/passwd:ro  # this is for database security
      - /home/pablo/local-docker-volumes/pgdbs/data_para_keycloak:/var/lib/postgresql/data/pgdata  # host directory should be owned by current user
    env_file:
      - ./database.dev.env
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    container_name: pgadmin_blog
    image: "dpage/pgadmin4:6.11"
    user: 1000:1000  # current user (pablo). Get this info with $(id -u):$(id -g)
    volumes:
      - /etc/passwd:/etc/passwd:ro  # this is for database security
      - /home/pablo/local-docker-volumes/pgadmin/para_keycloak/data:/var/lib/pgadmin
      - /home/pablo/local-docker-volumes/pgadmin/para_keycloak/logs:/var/log/pgadmin
      - /home/pablo/local-docker-volumes/pgadmin/para_keycloak/servers.json:/pgadmin4/servers.json
      - /home/pablo/local-docker-volumes/pgadmin/para_keycloak/config_distro.py:/pgadmin4/config_distro.py
    env_file:
      - ./database.dev.env
    ports:
      - "5050:80"
    networks: 
      - backend

  keycloak:
    container_name: keycloak_blog
    #image: "jboss/keycloak:16.1.1"
    image: "quay.io/keycloak/keycloak:19.0.1"
    command: ["start-dev"]
    env_file:
      - ./quai.io.keycloak.dev.env
      #- ./jboss.keycloak.dev.env
    depends_on:
      - "postgres"
    ports:
      - "8180:8080"
      #- "8787:8787" # debug port
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge